CREATE TABLE tb_loans (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
create_at TIMESTAMP NOT NULL,
pay_day TIMESTAMP,
update_at TIMESTAMP,

  user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,

    CONSTRAINT fk_loan_user
        FOREIGN KEY (user_id)
        REFERENCES tb_user(id),

    CONSTRAINT fk_loan_book
        FOREIGN KEY (book_id)
        REFERENCES tb_books(id)

);